config/routes.rb
Rails.application.routes.draw do
  resources :ads
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'ads#index'
end

app/models/ad.rb
class Ad < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: [:show, :edit, :update, :destroy]

  # GET /ads
  # GET /ads.json
  def index
    if params[:type].present?
      @ads = Ad.where(typ: params[:type])
    else  
      @ads = Ad.all
    end  
    # @ads = Ad.all
  end

  # GET /ads/1
  # GET /ads/1.json
  def show
  end

  # GET /ads/new
  def new
    @ad = Ad.new
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads
  # POST /ads.json
  def create
    @ad = Ad.new(ad_params)

    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: 'Ad was successfully created.' }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1
  # PATCH/PUT /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: 'Ad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_params
      params.require(:ad).permit(:name, :size, :colour, :description, :base, :dryingtime, :coverage, :image, :typ)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ads/_form.html.erb
<%= form_with(model: ad, local: true) do |form| %>
  <% if ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

      <ul>
      <% ad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :ad_name %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size, id: :ad_size %>
  </div>

  <div class="field">
    <%= form.label :colour %>
    <%= form.text_field :colour, id: :ad_colour %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :ad_description %>
  </div>

  <div class="field">
    <%= form.label :base %>
    <%= form.text_field :base, id: :ad_base %>
  </div>

  <div class="field">
    <%= form.label :dryingtime %>
    <%= form.text_field :dryingtime, id: :ad_dryingtime %>
  </div>

  <div class="field">
    <%= form.label :coverage %>
    <%= form.text_field :coverage, id: :ad_coverage %>
  </div>

  <div class="field">
  <%= form.label :type %><br>
  <%= form.text_field :typ %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :ad_image %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ads/edit.html.erb
<h1>Editing Ad</h1>

<%= render 'form', ad: @ad %>

<%= link_to 'Show', @ad %> |
<%= link_to 'Back', ads_path %>

app/views/ads/index.html.erb
<% @ads.each  do |ad| %>
  <div class="col-md-3">
    <div class="thumbnail">
       <h5><%= link_to ad.name, ad %></h5>
       <%= image_tag ad.image ,class: "img-responsive" %>  
        <div class="caption">
          <small><p class="text-right">Stock code: <%=ad.productcode%></p></small>  
          <h6 class="text-danger" >from £<%=ad.price %> </h6>
          
          
        
          
      </div>
    </div>
  </div>

<% end %> 

app/views/ads/new.html.erb
<h1>New Ad</h1>

<%= render 'form', ad: @ad %>

<%= link_to 'Back', ads_path %>

app/views/ads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ad.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @ad.size %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @ad.colour %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ad.description %>
</p>

<p>
  <strong>Base:</strong>
  <%= @ad.base %>
</p>

<p>
  <strong>Dryingtime:</strong>
  <%= @ad.dryingtime %>
</p>

<p>
  <strong>Coverage:</strong>
  <%= @ad.coverage %>
</p>

<%= link_to 'Edit', edit_ad_path(@ad) %> |
<%= link_to 'Back', ads_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rustins</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/ads">Rustin Paints</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        <form class="navbar-form navbar-left">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
    
    <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Products <span class="caret"></span></a>
         
          <ul class="dropdown-menu">
            <li><%= link_to("Wood preparation", ads_path(type: "wood_preparation")) %></li>
            <li role="separator" class="divider"></li>
            
            <li><%= link_to("Outdoor wood finishes", ads_path(type: "outdoor_wood_finishes")) %></li>
            <li role="separator" class="divider"></li>
            
            <li><%= link_to("Indoor wood finishes", ads_path(type: "indoor_wood_finishes")) %></li> 
            <li role="separator" class="divider"></li>
            
            <li><%= link_to("Floor finishes", ads_path(type: "floor_finishes")) %></li>
            <li role="separator" class="divider"></li>
            
            <li><%= link_to("Specjality products", ads_path(type: "speciality_products")) %></li>
            <li role="separator" class="divider"></li>
            
            <li><%= link_to("Decorating products", ads_path(type: "decorating_products")) %></li>
            <li role="separator" class="divider"></li>
          
            <li><%= link_to("Renowators", ads_path( type: "renovators")) %></li>   

          </ul>
        </li>

         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin commands <span class="caret"></span></a>
          <ul class="dropdown-menu">
          
          </ul>
        </li>


      
        
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


    <div class="container-fluid"> 
      <%= yield %>
    </div>  
  </body>
</html>